[mypy]
python_version = 3.13
strict = True
mypy_path = tools
explicit_package_bases = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-emu6502_c64_bindings]
ignore_missing_imports = True

[mypy-cluster_emu_patch]
ignore_missing_imports = True
